
export const LANGUAGE_OPTIONS = [
  "English",
  "Hindi",
  "Spanish",
  "French",
  "German",
  "Mandarin Chinese",
  "Arabic",
  "Japanese",
  "Korean",
  "Portuguese",
  "Russian",
  "Italian",
  "Bengali",
  "Urdu",
  "Turkish",
  "Tamil",
  "Telugu",
  "Marathi",
  "Gujarati",
  "Punjabi",
  "Malayalam",
  "Kannada",
  "Filipino (Tagalog)",
  "Vietnamese",
  "Swahili",
  "Dutch",
  "Persian (Farsi)",
  "Thai",
  "Greek",
  "Other"
];

export const NUTRITIONIST_SPECIALIZATIONS = [
  "Clinical Nutrition",
  "Sports Nutrition",
  "Pediatric Nutrition",
  "Geriatric Nutrition",
  "Weight Management",
  "Diabetes & Metabolic Disorders",
  "Cardiac Nutrition",
  "Renal Nutrition",
  "Digestive / Gut Health",
  "Food Allergies & Intolerances",
  "Plant-Based / Vegan Nutrition",
  "Nutrition Counseling & Lifestyle Coaching",
  "Prenatal & Maternal Nutrition",
  "Immunity & Wellness"
];

export const COUNTRIES = [
  "India",
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Netherlands",
  "Switzerland",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Ireland",
  "Brazil",
  "Mexico",
  "Argentina",
  "South Africa",
  "Nigeria",
  "Egypt",
  "Saudi Arabia",
  "United Arab Emirates",
  "Qatar",
  "Turkey",
  "Russia",
  "China",
  "Japan",
  "South Korea",
  "Singapore",
  "Malaysia",
  "Indonesia",
  "Philippines",
  "Thailand",
  "Vietnam",
  "New Zealand",
  "Bangladesh",
  "Pakistan",
  "Sri Lanka",
  "Nepal",
];

export const GENDERS = ["Male", "Female", "Other"];